source "https://rubygems.org"

gemspec
ruby "~> 3.0"
# gem 'activerecord', '~> 7', '>= 7', require: 'active_record'
gem "linkeddata", "~> 3.2.0"
gem "rake", "~> 13.0"
gem "rdf-raptor", "~> 3.1.0"
gem "require_all"
gem "rest-client", "~>2.1.0"
gem "rspec", "~> 3.11.0"
gem "rubocop"
gem "ruby-debug-ide"
gem "shotgun"
gem "sinatra", "~> 2.2"
gem "json"
gem "sinatra-cross_origin"
gem "swagger-blocks", "~> 3.0.0"
gem "thin"
gem "uri"
gem "debase"
gem "xml-simple", "~>1.1.8"

